<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <title>윤은경 포트폴리오</title>
  <link rel="stylesheet" href="style.css">
  <!-- 구글 폰트 -->
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR&family=Playfair+Display&display=swap" rel="stylesheet">
</head>
<body>
  <header>
    <h1>윤은경</h1>
    <p>영상 / 미술 / 인터미디어 아트</p>
  </header>

  <section id="projects">
    <h2>작업물</h2>
    <ul>
      <li><a href="projects/project1.html">Project 1</a></li>
      <li><a href="projects/project2.html">Project 2</a></li>
    </ul>
  </section>

  <footer>
    <p>Contact: zz090788@icloud.com</p>
  </footer>
</body>
</html>
